---
name: "SARIF to Slack notification"
author: "Yevhen Fabizhevskyi"
description: "GitHub action sends notification to Slack based on SARIF file"
branding:
  icon: message-square
  color: red
inputs:
  slack-webhook:
    description: Target Slack webhook URL.
    required: true
  sarif-path:
    description: |
      Path to the directory with SARIF files or to the SARIF file itself. Separate
      Slack messages will be sent for each SARIF file found in the directory.
    required: true
  log-level:
    description: |
      Log level of output. Possible options are "silly", "trace", "debug", "info",
      "warning", "error", "fatal". This parameter is ignored if CI pipeline is
      running in debug mode, e.g. ACTIONS_STEP_DEBUG is set to "true".
    required: false
    default: info
  color:
    description: What color of the message should be in hex format.
    required: false
    default: "#ff0000"
  username:
    description: Slack message username.
    required: false
  icon-url:
    description: Slack message icon.
    required: false
  header:
    description: Slack message header.
    required: false
  include-header:
    description: Whether to include header in the message.
    required: false
    default: "true"
  footer:
    description: Slack message footer.
    required: false
  include-footer:
    description: Whether to include footer in the message.
    required: false
    default: "true"
  actor:
    description: Who triggered the run.
    required: false
    default: ${{ github.actor }}
  include-actor:
    description: Whether to include actor in the message.
    required: false
    default: "true"
  include-run:
    description: Whether to include run in the message.
    required: false
    default: "true"
runs:
  using: "node20"
  main: "dist/index.js"
