---
name: "SARIF to Slack notification"
author: "Yevhen Fabizhevskyi"
description: "GitHub action sends notification to Slack based on SARIF file"
branding:
  icon: message-square
  color: red
inputs:
  slack-webhook:
    description: Target Slack webhook URL.
    required: true
  sarif-path:
    description: |
      Path to the directory with SARIF files or to the SARIF file itself. Separate
      Slack messages will be sent for each SARIF file found in the directory.
    required: true
  log-level:
    description: |
      Log level of output. Possible options are "silly", "trace", "debug", "info",
      "warning", "error", "fatal". This parameter is ignored if CI pipeline is
      running in debug mode, e.g. ACTIONS_STEP_DEBUG is set to "true".
    required: false
    default: info
  log-template:
    description: |
      Specifies the custom log message template to format log outputs, using the
      same template format as the tslog npm library. More details here:
      https://github.com/fullstack-build/tslog?tab=readme-ov-file#pretty-templates-and-styles-color-settings
    required: false
    default: "[{{logLevelName}}] [{{name}}] {{dateIsoStr}} "
  calculate-by:
    description: |
      Specifies how the summary results in the Slack message are calculated from
      the SARIF file(s) analysis. Possible values:
      - "level": Calculates results by the "results[].level" property, or by the
        "rules[].properties['problem.severity']" property if "results[].level"
        property does not exist (such as error, warning, note).
      - "severity": Calculates results by the "rules[].properties['security-severity']"
        property that has CVSS score. Then this score is transformed into severity
        value (such as critical, high, medium, low, none).
    required: false
    default: "severity"
  group-by:
    description: |
      Controls how analysis results from the SARIF file are grouped and summarized
      in the Slack message. Possible values:
      - "tool-name": Groups results by tool name, combining and summarizing results
        from all runs that use the same tool.
      - "run": Groups results by each individual SARIF run, even if multiple runs
        use the same tool.
      - "total": No grouping; combines all results from all runs and provides a
        single overall summary.
    required: false
    default: "tool-name"
  color:
    description: What color of the message should be in hex format.
    required: false
    default: "#ff0000"
  username:
    description: Slack message username.
    required: false
  icon-url:
    description: Slack message icon.
    required: false
  header:
    description: Slack message header.
    required: false
  include-header:
    description: Whether to include header in the message.
    required: false
    default: "true"
  footer:
    description: Slack message footer.
    required: false
  include-footer:
    description: Whether to include footer in the message.
    required: false
    default: "true"
  actor:
    description: Who triggered the run.
    required: false
    default: ${{ github.actor }}
  include-actor:
    description: Whether to include actor in the message.
    required: false
    default: "true"
  include-run:
    description: Whether to include run in the message.
    required: false
    default: "true"
runs:
  using: "node20"
  main: "dist/index.js"
