---
name: "SARIF to Slack notification"
author: "Yevhen Fabizhevskyi"
description: "GitHub action sends notification to Slack based on SARIF file"
branding:
  icon: message-square
  color: red
inputs:
  slack-webhook:
    description: Target Slack webhook URL.
    required: true
  username:
    description: Slack message username.
    required: false
  icon-url:
    description: Slack message icon.
    required: false
  color:
    description: |
      Default color of the Slack message if specific color was not found. It is
      a fallback option.
    required: false
  color-empty:
    description: |
      Color of the message when there are no findings in the provided SARIF file(s).
    required: false
  color-severity-critical:
    description: |
      Color of the message when at least one finding has "Critical" severity.
    required: false
  color-severity-high:
    description: |
      Color of the message when at least one finding has "High" severity.
    required: false
  color-severity-medium:
    description: |
      Color of the message when at least one finding has "Medium" severity.
    required: false
  color-severity-low:
    description: |
      Color of the message when at least one finding has "Low" severity.
    required: false
  color-severity-none:
    description: |
      Color of the message when at least one finding has "None" severity.
    required: false
  color-severity-unknown:
    description: |
      Color of the message when at least one finding has "Unknown" severity.
    required: false
  color-level-error:
    description: |
      Color of the message when at least one finding has "Error" level.
    required: false
  color-level-warning:
    description: |
      Color of the message when at least one finding has "Warning" level.
    required: false
  color-level-note:
    description: |
      Color of the message when at least one finding has "Note" level.
    required: false
  color-level-none:
    description: |
      Color of the message when at least one finding has "None" level
    required: false
  color-level-unknown:
    description: |
      Color of the message when at least one finding has "Unknown" level
    required: false
  sarif-path:
    description: |
      Path to the directory with SARIF files or to the SARIF file itself. Separate
      Slack messages will be sent for each SARIF file found in the directory.
    required: true
  sarif-path-recursive:
    description: |
      If provided SARIF path is a directory, whether to traverse provided SARIF
      path recursively or not.
    required: false
    default: "false"
  sarif-file-extension:
    description: |
      Extension for SARIF files. Possible values: sarif, json.
    required: false
    default: "sarif"
  log-level:
    description: |
      Log level of output. Possible options are "silly", "trace", "debug", "info",
      "warning", "error", "fatal". This parameter is ignored if CI pipeline is
      running in debug mode, e.g. ACTIONS_STEP_DEBUG is set to "true".
    required: false
    default: info
  log-template:
    description: |
      Specifies the custom log message template to format log outputs, using the
      same template format as the tslog npm library. More details here:
      https://github.com/fullstack-build/tslog?tab=readme-ov-file#pretty-templates-and-styles-color-settings
    required: false
    default: "[{{logLevelName}}] [{{name}}] {{dateIsoStr}} "
  log-colored:
    description: Whether logs should be colored or not.
    required: false
    default: "true"
  header:
    description: Slack message header.
    required: false
  include-header:
    description: Whether to include header in the message.
    required: false
    default: "true"
  footer:
    description: Slack message footer.
    required: false
  include-footer:
    description: Whether to include footer in the message.
    required: false
    default: "true"
  actor:
    description: Who triggered the run.
    required: false
    default: ${{ github.actor }}
  include-actor:
    description: Whether to include actor in the message.
    required: false
    default: "true"
  include-run:
    description: Whether to include run in the message.
    required: false
    default: "true"
  representation:
    description: |
      Slack message representation. Possible values: compact-group-by-run-per-level,
      compact-group-by-run-per-severity, compact-group-by-tool-name-per-level,
      compact-group-by-tool-name-per-severity, compact-group-by-sarif-per-level,
      compact-group-by-sarif-per-severity, compact-total-per-level,
      compact-total-per-severity.
    required: false
    default: "compact-group-by-tool-name-per-severity"
  send-if:
    description: |
      Condition on when Slack message should be sent. Possible values: severity-critical,
      severity-high, severity-high-or-higher, severity-medium, severity-medium-or-higher,
      severity-low, severity-low-or-higher, severity-none, severity-none-or-higher,
      severity-unknown, severity-unknown-or-higher, level-error, level-warning,
      level-warning-or-higher, level-note, level-note-or-higher, level-none,
      level-none-or-higher, level-unknown, level-unknown-or-higher, always, some,
      empty, never.
    required: false
    default: "always"
runs:
  using: "node24"
  main: "dist/index.js"
