---
name: Functional Tests

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      sarif-file:
        description: SARIF file to send
        required: true
        default: codeql-csharp.sarif
        type: choice
        options:
          - codeql-csharp.sarif
          - codeql-go.sarif
          - codeql-python.sarif
          - codeql-ruby.sarif
          - codeql-typescript.sarif
          - grype-container.sarif
          - snyk-csharp-nuget.sarif
          - snyk-elixir-hex.sarif
          - snyk-go-gomodules.sarif
          - snyk-java-gradle.sarif
          - snyk-java-maven.sarif
          - snyk-javascript-npm.sarif
          - snyk-javascript-pnpm.sarif
          - snyk-javascript-yarn.sarif
          - snyk-php-composer.sarif
          - snyk-python-pip.sarif
          - snyk-python-poetry.sarif
          - snyk-ruby-rubygems.sarif
          - snyk-scala-sbt.sarif
          - snyk-swift-swift.sarif
          - trivy-iac.sarif
      color:
        description: What color of the message should be in hex representation.
        required: false
        default: "#ff0000"
        type: string
      username:
        description: Slack message username.
        required: false
        type: string
      header:
        description: Slack message header.
        required: false
        default: "SARIF results"
        type: string
      include-header:
        description: Whether to include header in the message.
        required: false
        default: true
        type: boolean
      footer:
        description: Slack message footer.
        required: false
        type: string
      include-footer:
        description: Whether to include footer in the message.
        required: false
        default: true
        type: boolean
      actor:
        description: Who triggered the run.
        required: false
        type: string
      include-actor:
        description: Whether to include actor in the message.
        required: false
        default: true
        type: boolean
      include-run:
        description: Whether to include run in the message.
        required: false
        default: true
        type: boolean

defaults:
  run:
    shell: sh

jobs:
  functional-tests:
    name: Send
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Send message
        uses: ./
        with:
          slack-webhook: "${{ secrets.TMP_EUGENE_SLACK_WEBHOOK }}"
          sarif-path: "test-data/sarif/${{ inputs.sarif-file }}"
          color: "${{ inputs.color }}"
          username: "${{ inputs.username == '' && github.repository || inputs.username }}"
          icon: "https://cdn-icons-png.flaticon.com/512/9070/9070006.png"
          header: "${{ inputs.header }}"
          include-header: "${{ inputs.include-header }}"
          footer: "${{ inputs.footer == '' && format('Generated by <{0}/{1}|{1}>', github.server_url, github.repository) || inputs.footer }}"
          include-footer: "${{ inputs.include-footer }}"
          actor: "${{ inputs.actor == '' && github.actor || inputs.actor }}"
          include-actor: "${{ inputs.include-actor }}"
          include-run: "${{ inputs.include-run }}"
