---
name: Security

on: # yamllint disable-line rule:truthy
  pull_request: {}
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      security-type:
        description: What Security scanning you would like to run?
        required: false
        default: "all"
        type: choice
        options: ["all", "sca", "code-scanning"]

jobs:
  sast:
    name: SAST
    permissions:
      contents: read
      security-events: write
    uses: fabasoad/reusable-workflows/.github/workflows/wf-security-sast.yml@main
    with:
      code-scanning: ${{ (github.event.inputs.security-type || 'all') == 'all' || github.event.inputs.security-type == 'code-scanning' }}
      sca: ${{ (github.event.inputs.security-type || 'all') == 'all' || github.event.inputs.security-type == 'sca' }}
